### ISSUE TITLE
how to add node at (ZIP)

### ISSUE THREAD

**Issue by ghost** [Z-WavePublic/libzwaveip#46] opened 2017-11-04 09:18 UTC
I am stuck at (ZIP) addnode
(ZIP)
Please help me out, what to give to add a node

**Comment by miline** [comment] 2017-11-04 14:09
Can you elaborate more on what you are doing. "addnode" puts ZIP Gateway into add mode and then you can initiate the z-wave node to be included by some button.So basically you just want to do "addnode" and then ZIP Gateway is listening for incoming requests.

**Comment by anta** [comment] 2018-08-28 10:51
@appalanaidugollu Does the issue persist for you? If yes, could you describe more about the steps, setup, and errors you are having?

**Comment by anta** [comment] 2018-09-06 12:31
Closing this for now since the issue is not clear.

**Closed as completed by anta** 2018-09-06 12:31 UTC
